% WAP that implements Semantic Networks(ATN/RTN).

class(person).
class(male).
class(female).
class(height).
class(weight).
class(age).
isa(male,person).
isa(female,person).
isa(jane,female).
isa(john,male).
isa(david,male).
owns(john,house).
owns(jane,house).
owns(david,car).
hasprop(person,[height,weight,age]).
hasa(john,height,171).
hasa(john,weight,70).
hasa(john,age,31).
hasa(jane,height,154).
hasa(jane,weight,49).
hasa(jane,age,24).
hasa(david,height,167).
hasa(david,weight,69).
hasa(david,age,28).
isperson(X):-isa(X,person),!.
isperson(X):-isa(Y,person),isa(X,Y).
get_prop(X,[H|[]],P):-hasa(X,H,Y),append([],[Y],P).
get_prop(X,[H|T],P):-get_prop(X,T,P1),hasa(X,H,Y),append([Y],P1,P).
prop_of(X,P):-isperson(X),hasprop(person,P1),get_prop(X,P1,P),!.
hascar(X1):-isperson(X1),\+(class(X1)),owns(X1,car).
